tunnel: 6faf2711-6e9e-4b02-a65b-d14e65d5a59a
credentials-file: C:\Users\Keneth Dale Tuazon\.cloudflared\6faf2711-6e9e-4b02-a65b-d14e65d5a59a.json

ingress:
  - hostname: jusconsultus.online
    service: http://localhost:3000
  - hostname: www.jusconsultus.online
    service: http://localhost:3000
  - service: http_status:404
